# 服务配置
server:
  port: 8320
  compression:
    enabled: true
    
# Spring相关配置
spring:
  application:
    name: bank-service
  profiles: 
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.6:3306/bank_db?useUnicode=true&characterEncoding=UTF-8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: bank
    password: test123
    hikari:
      connection-test-query: select 1 from dual
  servlet:
    multipart:
      # 最上传文件大小
      max-file-size: 100MB
      # 最大请求数据大小
      max-request-size: 20MB

# 集成MyBatis  
mybatis:   
  mapperLocations: classpath*:mybatis/mapper/**/*.xml
  typeAliasesPackage: com.efe.ms.**.model
  #configLocation: classpath:mybatis/config/mybatis-config.xml
  configuration-properties: 
    # 数据库方言
    helperDialect: mysql 
    # RowBounds参数offset作为PageNum使用 - 默认不使用
    offsetAsPageNum: true 
    # RowBounds是否进行count查询 - 默认不查询
    rowBoundsWithCount: true
    # 当设置为true的时候，如果pagesize设置为0（或RowBounds的limit=0），就不执行分页，返回全部结果
    pageSizeZero: false
    # 分页合理化
    reasonable: false
    # 是否支持接口参数来传递分页参数，默认false
    #supportMethodsArguments: true
    #params: pageNum=pageNumKey;pageSize=pageSizeKey;

# 自定义环境配置  
custom-env: 
  # 虚拟目录配置 
  virtual-path-pattern: /istorage/**
  virtual-dir-pattern: file:D:/bankService/files/
  linux-virtual-dir-pattern: file:/usr/bankService/website/files/    

# 日志
logging: 
  config: classpath:log-config/logback-${spring.profiles.active}.xml
  
  
  
  
  